### ISSUE TITLE
Get Riak host/port from env, if available. [JIRA: CLIENTS-605]

### ISSUE THREAD

**Issue by lukebakken** [basho/riak-php-client#105]
I've got code like the following in the Go and Node.js clients that reads the host and port for Riak from the environment, if present:

https://github.com/basho/riak-go-client/blob/master/globals_test.go#L39-L59

This facilitates running tests against a production Riak vs devrel.

**Comment by lukebakken** [comment]
Keep the default at `8098`, of course. I won't have to edit `tests/TestCase.php` to run tests.

**Comment by lukebakken** [comment]
Running the `php` branch of `riak-client-tools` works too, so (shrug) :smile:

**Comment by alexmoore** [comment]
@lukebakken I knew that would come in handy for those that aren't fully virtualized :)

**Comment by christophermancini** [comment]
@alexmoore quiet you! :stuck_out_tongue_winking_eye:
