### ISSUE TITLE
How delete keys from some parameters ? [JIRA: CLIENTS-684]

### ISSUE THREAD

**Issue by Ducatel** [basho/riak-php-client#112]
Hi everybody,

I'm trying to find a way to delete a set of keys.

I store data with this format:
```
$dataToStore = [
            "date" => time(),
            "data" => $myData
        ];
```
I didn't find how I can delete keys with condition like `date < $anotherTimestamp`.
Is it possible ?

Can you help me on this point ?
Thanks for your help ;)

**Comment by christophermancini** [comment]
Hi @Ducatel, currently there is not a way to automatically delete keys from within Riak KV out of the box at this time. You would have to develop a background / cron process to determine which keys are "expired" then manually delete them.

One way you could do this is with Yokozuna (Solr), which allows you to set search indexes for a bucket type to index your "date" field, then do Solr range lookups on that index.

As part of our development of Riak TS (Time Series), we will be adding support for data to expire efficiently as an out of the box feature. Unfortunately, I do not have a timeline for that development.

Also, there is possibility you can configure expiration of keys directly in the backend storage engine (bitcask, leveldb, etc) you are using, but it is not backend agnostic or configurable within Riak. Which would require knowledge of your chosen backend and what behaviors that could introduce with your use of Riak.

**Comment by Ducatel** [comment]
Ok, so I will use Yokozuna to do it ;) 
http://docs.basho.com/riak/latest/dev/using/search/

Thanks for your help.

**Comment by christophermancini** [comment]
Your quite welcome! :)
