### ISSUE TITLE
problem of Store XML file into riak [JIRA: CLIENTS-816]

### ISSUE THREAD

**Issue by txl1290** [basho/riak-php-client#119]
Dear Mancini,
	Recently, I use basho/riak-php-client between php program and riak server. And I want store a xml file into riak, I set content-type to text/xml,but it doesn't work. I check the source code, and find "rawurlencode($data)" in riak-php-client/src/Riak/Command/Object.php line 50. This causes xml label no longer has any effect.
	I wish to konw the necessity of the code. I delete urlencode and store xml file successfully, but I'm afraid about influencing the correctness of the project.

Best Wishes!

Xiaolong Tang

**Comment by christophermancini** [comment]
Hi @txl1290, thanks for submitting the issue, I will try to trouble shoot it. Do you have a snippet of code so that I can reproduce the issue?

**Comment by txl1290** [comment]
Hi @christophermancini ,
I found the reason. It's my mistake. I use storeObject to store xml. But I use the xml through riak http request. This doesn't contain the urldecode handle. 
I use fetchObject and now it's ok.

sorry to waste your time.
Best Wishes!
Xiaolong Tang
