### ISSUE TITLE
Binary data - decode breaks submission [JIRA: CLIENTS-918]

### ISSUE THREAD

**Issue by benscott** [basho/riak-php-client#122]
I'm trying to submit binary image data, for example:

        $object = new Object();
        $object->setContentType('image/jpeg');
        $object->setContentEncoding("base64");
        $object->setData([BINARY IMAGE]);

        $command = (new Command\Builder\StoreObject([RIAK]))
            ->withObject($object)
            ->atLocation([LOCATION])
            ->build()
           ->execute()

The problem is the binary data gets encoded before submission to Riak, so it seems the binary data isn't stored properly in Riak (the image returned out of Riak over HTTP isn't displayable). To fix this we're checking the object's content encoding, and if binary/base64 returning the object data unencoded (see pull request).

**Comment by Basho-JIRA** [comment]
PRs:
* https://github.com/basho/riak-php-client/pull/131 (OPEN)
* https://github.com/basho/riak-php-client/pull/123 (CLOSED)
* https://github.com/basho/riak-php-client/pull/129 (CLOSED) 

***[posted via JIRA by Derek Somogyi]***

**Comment by christophermancini** [comment]
This should be resolved via the changes in #131

**Comment by Basho-JIRA** [comment]
This is done

On Mon, Oct 17, 2016, 12:09 PM Derek Somogyi (JIRA) <

-- 
Sincerely,

Christopher Mancini
-----------------------------

employee = {
    purpose: solve problems with code,
    phone:    7164625591,
    email:     cmancini@basho.com,
    github:    http://www.github.com/christophermancini
}
 

***[posted via JIRA by Christopher Mancini]***
