### ISSUE TITLE
PHP Client not reporting Internal Server Errors from Riak [JIRA: CLIENTS-927]

### ISSUE THREAD

**Issue by Bob-The-Marauder** [basho/riak-php-client#125]
Taking the example from http://docs.basho.com/riak/kv/2.1.4/developing/getting-started/php/querying/ and deliberately choosing bitcask as our back end (no index support), running the script gives the following output:-
![php output](https://cloud.githubusercontent.com/assets/20081341/16988779/8399a81e-4ecc-11e6-8cf7-c8f7382175fa.png)
where the "Janes's Orders" and "October's Orders" queries made against an index appear to merely be empty - nothing visible on screen, nothing I can find in the Riak logs.

However, if we check the Wireshark trace for the whole exercise we can see the queries being made and returned. Jane's Orders is packet 67 and the reply with an Internal Server Error is packet 70. Again, the "October's Orders" query is packet 73 and the reply with another Internal Server Error is packet 76.
[phpclient_code500_not_displayed.pcapng.zip](https://github.com/basho/riak-php-client/files/373833/phpclient_code500_not_displayed.pcapng.zip)

Please can we fix it so that the PHP Client either reports or at least logs Internal Server Errors?

**Comment by christophermancini** [comment]
Hi @Bob-The-Marauder, I am working on a fix for this issue and hopeful to have it resolved within the next few days. Thanks for reporting it.

**Comment by Basho-JIRA** [comment]
[~cmancini] - Can this be closed?  The PR is closed... 

***[posted via JIRA by Derek Somogyi]***

**Comment by Basho-JIRA** [comment]
Yes

On Thu, Sep 1, 2016, 1:48 PM Derek Somogyi (JIRA) <

-- 
Sincerely,

Christopher Mancini
-----------------------------

employee = {
    purpose: solve problems with code,
    phone:    7164625591,
    email:     cmancini@basho.com,
    github:    http://www.github.com/christophermancini
}
 

***[posted via JIRA by Christopher Mancini]***
