### ISSUE TITLE
responseHeaderCallback is truncating datetime-related header fields [JIRA: CLIENTS-948]

### ISSUE THREAD

**Issue by heylarson** [basho/riak-php-client#128]
Header fields like Last-Modified, are being truncated incorrectly due to the colon character associated with datetime fields.  The explode function delimiter is set to the colon to parse the header key, and header value but is truncating any header values that have a colon character in it.

Found in: basho/riak/src/Riak/Api/Http.php:607

A proposed fix would be to change that line to:
```
list ($key, $value) = explode(':', $header, 2);
```

**Comment by christophermancini** [comment]
I will check into this issue, thanks for reporting it.

**Comment by christophermancini** [comment]
@heylarson Thanks again for all your contributions to the library. I fixed this bug in #140. Let me know if it doesn't resolve your issue.

**Comment by heylarson** [comment]
Looks good!
