### ISSUE TITLE
Remove client-side-only quorums [JIRA: CLIENTS-89]

### ISSUE THREAD

**Issue by seancribbs** [basho/riak-php-client#46]
The various "setR"/"getR" accessors on Bucket and Client should be removed in favor of using bucket properties and request-time quorum options. This will bring it in line with the patterns used in the Python and Ruby clients and remove the inherent ambiguity and leakiness.

/cc @MarcoDeBortoli

**Comment by Basho-JIRA** [comment]
Will be accomplished via new PHP 2.0 client. 

***[posted via JIRA by Derek Somogyi]***
