### ISSUE TITLE
Remove new_/get_binary, replace with serializers and lazy codec

### ISSUE THREAD

**Issue by seancribbs** [basho/riak-php-client#47]
Reification of serialized types should be dependent on whether the application needs the types or not, not how the object was fetched. For example, an application might want to fetch in one media type and rewrite the object in another, but the current structure would make that difficult, ignoring the newly assigned media type if the object was previously automatically deserialized.

For reference, a similar refactoring: https://github.com/basho/riak-python-client/pull/213

**Comment by christophermancini** [comment]
This is nolonger applicable due to 2.x rewrite.
