### ISSUE TITLE
Riak 2.0 Feature: CRDTs [JIRA: CLIENTS-60]

### ISSUE THREAD

**Issue by kuenishi** [basho/riak-php-client#58]
Per basho/riak#354 , Riak 2.0 will bring more CRDTs, including sets, vector clocks, flags, and more to Riak.

- [ ] Support maps
- [ ] Support sets
- [ ] Support counters

**Comment by Basho-JIRA** [comment]
This has been completed and will be released as part of the 2.0.x release coming up within the next couple of weeks. Can be seen within the 2.0.x branch. 

***[posted via JIRA by Christopher Mancini]***
