### ISSUE TITLE
Skip urldecode in indexSearch and getKeys [JIRA: CLIENTS-90]

### ISSUE THREAD

**Issue by Addeventure** [basho/riak-php-client#65]
With urlencoding enabled in Riak HTTP API, 2i and list keys result should not be urldecoded in PHP as it then gets decoded twice:

```php
$bucket->newBinary('hello%3Aworld', 'foobar')->setIndex('someIndex', 'bin', array('hi'))->store();
$link = reset($bucket->indexSearch('someIndex', 'bin', 'hi'));
echo $link->getKey();
```

This incorrectly produces "hello:world" instead of "hello%3Aworld". Simply removing urldecode (or making it an optional config value?) solves the issue.

**Comment by Basho-JIRA** [comment]
[~cmancini], I'm guessing this can be closed.  Please confirm.  Thanks. 

***[posted via JIRA by Derek Somogyi]***

**Comment by christophermancini** [comment]
No response to confirm that this is still an issue.

**Comment by Addeventure** [comment]
Oops, i missed this, sorry!

I am still on riak 1.3.2 so i cannot confirm how this behaves in 1.4.x or
2.x.
Den 10 apr 2015 02:52 skrev "Christopher Mancini" <notifications@github.com

**Comment by christophermancini** [comment]
Hey @Addeventure , glad you posted back. Is this still a problem for you with the 1.4.x (master branch - I say 1.4 because of the features supported, but it works with 1.3.x) of the client?

If so, I can reopen and investigate.

**Comment by Addeventure** [comment]
Yes, the lines causing the issue are:
https://github.com/basho/riak-php-client/blob/master/src/Basho/Riak/Bucket.php#L393
https://github.com/basho/riak-php-client/blob/master/src/Basho/Riak/Bucket.php#L419

To reproduce, create a new object using a key like 'hello%3Aworld'. Retrieve the key using indexSearch or getKeys. The returned data will contain the key 'hello:world'

I am not sure why the urldecode is there in the first place though. Perhaps related to around problems with the deprecated "http_url_encoding" config option? I am just guessing...
Not sure if this gives any clues but the code was originally added here https://github.com/basho/riak-php-client/commit/771b285 when 2i support was added to the library (Nov 23, 2011).

**Comment by christophermancini** [comment]
Alright, after we get the rewritten client released, I will investigate this for you.

**Comment by christophermancini** [comment]
@Addeventure Can you checkout my PR and give it a :+1: if it looks good?
