### ISSUE TITLE
Document setting up environment for running test suite. [JIRA: CLIENTS-357]

### ISSUE THREAD

**Issue by lukebakken** [basho/riak-php-client#96]
For instance, on Arch Linux:

```
sudo pacman -S php
curl -sS https://getcomposer.org/installer | php
sudo mv composer.phar /usr/local/bin/composer
sudo chmod 755 /usr/local/bin/composer
composer install
./vendor/bin/phpunit
```

There is also no script to set up Riak to run tests at this point.

See issues:
basho/riak-nodejs-client#43
basho/riak-dotnet-client#270

**Comment by lukebakken** [comment]
Also, make a note that `phar` and `openssl` must be enabled in `php.ini`

**Comment by christophermancini** [comment]
Attempted to address this in #109
